// flow-typed signature: e5d798b4519ee4e6e0e41d672730e8fa
// flow-typed version: <<STUB>>/lodash-match-pattern_v^1.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash-match-pattern'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash-match-pattern' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash-match-pattern/_parser' {
  declare module.exports: any;
}

declare module 'lodash-match-pattern/lib/helpers' {
  declare module.exports: any;
}

declare module 'lodash-match-pattern/lib/mixins' {
  declare module.exports: any;
}

declare module 'lodash-match-pattern/lib/normalize' {
  declare module.exports: any;
}

declare module 'lodash-match-pattern/tonic_example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash-match-pattern/_parser.js' {
  declare module.exports: $Exports<'lodash-match-pattern/_parser'>;
}
declare module 'lodash-match-pattern/index' {
  declare module.exports: $Exports<'lodash-match-pattern'>;
}
declare module 'lodash-match-pattern/index.js' {
  declare module.exports: $Exports<'lodash-match-pattern'>;
}
declare module 'lodash-match-pattern/lib/helpers.js' {
  declare module.exports: $Exports<'lodash-match-pattern/lib/helpers'>;
}
declare module 'lodash-match-pattern/lib/mixins.js' {
  declare module.exports: $Exports<'lodash-match-pattern/lib/mixins'>;
}
declare module 'lodash-match-pattern/lib/normalize.js' {
  declare module.exports: $Exports<'lodash-match-pattern/lib/normalize'>;
}
declare module 'lodash-match-pattern/tonic_example.js' {
  declare module.exports: $Exports<'lodash-match-pattern/tonic_example'>;
}
