// flow-typed signature: f0b1c5d0fd22dc70958d3abbf8c5fb4d
// flow-typed version: <<STUB>>/ps-node_v^0.1.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ps-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ps-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ps-node/lib/index' {
  declare module.exports: any;
}

declare module 'ps-node/test/node_process_for_test' {
  declare module.exports: any;
}

declare module 'ps-node/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ps-node/index' {
  declare module.exports: $Exports<'ps-node'>;
}
declare module 'ps-node/index.js' {
  declare module.exports: $Exports<'ps-node'>;
}
declare module 'ps-node/lib/index.js' {
  declare module.exports: $Exports<'ps-node/lib/index'>;
}
declare module 'ps-node/test/node_process_for_test.js' {
  declare module.exports: $Exports<'ps-node/test/node_process_for_test'>;
}
declare module 'ps-node/test/test.js' {
  declare module.exports: $Exports<'ps-node/test/test'>;
}
