// flow-typed signature: e7c03a4ac695e4a014530cf5ab6c79da
// flow-typed version: <<STUB>>/randexp_v^0.4.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randexp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'randexp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'randexp/build/randexp.min' {
  declare module.exports: any;
}

declare module 'randexp/gulpfile' {
  declare module.exports: any;
}

declare module 'randexp/lib/randexp' {
  declare module.exports: any;
}

declare module 'randexp/test/custom-prng-test' {
  declare module.exports: any;
}

declare module 'randexp/test/custom-range-test' {
  declare module.exports: any;
}

declare module 'randexp/test/main-test' {
  declare module.exports: any;
}

declare module 'randexp/test/sugar-test' {
  declare module.exports: any;
}

declare module 'randexp/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'randexp/build/randexp.min.js' {
  declare module.exports: $Exports<'randexp/build/randexp.min'>;
}
declare module 'randexp/gulpfile.js' {
  declare module.exports: $Exports<'randexp/gulpfile'>;
}
declare module 'randexp/lib/randexp.js' {
  declare module.exports: $Exports<'randexp/lib/randexp'>;
}
declare module 'randexp/test/custom-prng-test.js' {
  declare module.exports: $Exports<'randexp/test/custom-prng-test'>;
}
declare module 'randexp/test/custom-range-test.js' {
  declare module.exports: $Exports<'randexp/test/custom-range-test'>;
}
declare module 'randexp/test/main-test.js' {
  declare module.exports: $Exports<'randexp/test/main-test'>;
}
declare module 'randexp/test/sugar-test.js' {
  declare module.exports: $Exports<'randexp/test/sugar-test'>;
}
declare module 'randexp/test/tests.js' {
  declare module.exports: $Exports<'randexp/test/tests'>;
}
