// flow-typed signature: f949ff03e105fed22b37d687b121744a
// flow-typed version: <<STUB>>/request-promise_v^4.1.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-promise/errors' {
  declare module.exports: any;
}

declare module 'request-promise/lib/rp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-promise/errors.js' {
  declare module.exports: $Exports<'request-promise/errors'>;
}
declare module 'request-promise/lib/rp.js' {
  declare module.exports: $Exports<'request-promise/lib/rp'>;
}
