#! /bin/bash

srcname=`echo $1 | perl -npe 's/^.*\///; s/\.feature(\:\d*)?//'`
filename=`echo $1 | perl -npe "chop; \\\$_ = /\// ? \\\$_ : './src/universe/features/' . \\\$_ . '.feature'"`
cmd="node_modules/.bin/cucumberjs --require ./src/universe/features/${srcname}_test.js $filename"
echo $cmd
$cmd
