#! /bin/bash

srcname=`echo $1 | perl -npe 's/_service.*$//; s/^.*\///; s/\.feature(\:\d*)?//'`
filename=`echo $1 | perl -npe "chop; \\\$_ = /\// ? \\\$_ : './src/' . \\\$_ . '_service/features'"`
cmd="./node_modules/.bin/cucumberjs --format pretty --require ./src/${srcname}_service/features/internal_${srcname}_test.js $filename"
echo $cmd
$cmd
