#! /bin/bash

srcname=`echo $1 | perl -npe 's/^.*\///; s/\.feature(\:\d*)?//'`
filename=`echo $1 | perl -npe "chop; \\\$_ = /\// ? \\\$_ : './src/step_features/' . \\\$_ . '.feature'"`
cmd="node_modules/.bin/cucumberjs --require ./src/step_features/${srcname}_hooks.js $filename"
echo $cmd
$cmd
